name: Update Azure Resume Site Backend Files On Blob Storage

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy Azure Function Counter Files To Blob Storage
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          az storage file upload --account-name azresumeacct --share-name func-butterresume12c3f1b2408b --source ./backend/Counter/run.ps1 --path "site/wwwroot/Counter"
          az storage file upload --account-name azresumeacct --share-name func-butterresume12c3f1b2408b --source ./backend/Counter/function.json --path "site/wwwroot/Counter"
          
    - name: Purge Azure CDN Endpoint For Azure Resume Site
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "butterfieldtechresume" --name "butterfieldtech" --resource-group "terraVnetRg"

  # Azure logout
    - name: Logout Az Cli
      run: |
            az logout
      if: always()